package corba;

/**
* TaxApp/TaxHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./Tax.idl
* Monday, April 4, 2016 8:56:48 PM EDT
*/

public final class TaxHolder implements org.omg.CORBA.portable.Streamable
{
  public corba.Tax value = null;

  public TaxHolder ()
  {
  }

  public TaxHolder (corba.Tax initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = corba.TaxHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    corba.TaxHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return corba.TaxHelper.type ();
  }

}
