package corba;


/**
* TaxApp/TaxOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./Tax.idl
* Monday, April 4, 2016 8:56:48 PM EDT
*/

public interface TaxOperations 
{
  double getTaxRate (double gross);
  void shutdown ();
} // interface TaxOperations
